### ISSUE TITLE
Drop support for ancient java versions

### ISSUE THREAD

**Issue by slipset** [pmonks/CLJ-2253#2]
As of Clojure 1.10, Clojure only supports java 8 and upwards. 
A lot of crufty code can be removed if this lib follows suite

**Comment by pmonks** [comment]
Wow I hadn't heard that, but that's great news!

**Comment by pmonks** [comment]
Awaiting Clojure 1.10, at which point we'll have to make a decision about whether to drop support for older JVMs (that might still be in use with older versions of Clojure, which this library works just fine with).

**Comment by pmonks** [comment]
rev e8502c86e42c3c7fed3a4d3f43a160c394fe96db adds tests for some of these cases (combinations of Clojure & JVM versions).

**Comment by pmonks** [comment]
Given that some folks still use old JVM and/or Clojure versions, I'm wondering if this is actually a good idea.  wdyt @slipset ?

**Comment by pmonks** [comment]
Given we've already done the hard work of making this work across a wide variety of Clojure and JVM versions, I don't think we need to drop support for older stuff.  Why exclude those poor folks who are still stuck on older versions from their dreams of CLJ-2253 fulfillment?   :wink:
