### ISSUE TITLE
Use deps.edn and (possibly) lein-tools-deps

### ISSUE THREAD

**Issue by slipset** [pmonks/CLJ-2253#3]
SSIA

**Comment by pmonks** [comment]
Wasn't aware of tools.deps before - thanks for the pointer!

[edit] though I'm slightly confused how this would be useful here, given this library has no dependencies (beyond Clojure itself)?

**Comment by slipset** [comment]
I think it then easily be consumed by other libs using deps.edn

**Comment by pmonks** [comment]
Ah ok - clearly I need to read up on tools.deps some more then.  ;-)
