### ISSUE TITLE
Set up project to only allow 'Squash and Merge' when merging PRs

### ISSUE THREAD

**Issue by slipset** [pmonks/CLJ-2253#7]
This way we avoid merge-conflicts

**Comment by pmonks** [comment]
I assume this refers to turning off "Allow rebase merging" in these settings:
![image](https://user-images.githubusercontent.com/54865/42115690-c84fe670-7ba8-11e8-95ff-ca07eba4a747.png)

?  Or is there more to it than that?

Separately, I'm tempted to turn on branch protection for master, now that the CI pipeline is reasonably robust.  wdyt?

**Comment by slipset** [comment]
Yeah, so I'd uncheck `Allow merge commits`. 
And yes, I'm fine with protecting master branch

**Comment by pmonks** [comment]
Ok stand by...

**Comment by pmonks** [comment]
Done!  Let me know if you see anything untoward.
